//The template for this code was generated by Claude in accordance with the course's AI use policy
// However, all text and figures are my own.

export default function CatBoostSHAP() {
  return (
    <section className="w-full my-8">
      <h2 className="text-xl font-semibold mb-4">
        Injury Risk Prediction
      </h2>

      {/* OUTER CONTAINER */}
      <div
        style={{
          display: "grid",
          gridTemplateColumns: "minmax(0, 1fr) 320px",
          gap: "24px",
          alignItems: "start",
          width: "100%",
        }}
      >
        {/* LEFT: chart */}
        <div style={{ minWidth: 0 }}>
          <img
            src="/CatBoost SHAP Summary Plot.svg"
            alt="CatBoost Classifier SHAP Values"
            style={{
              width: "100%",
              display: "block",
              borderRadius: "8px",
              border: "1px solid #2a2a3e",
            }}
          />
        </div>

        {/* RIGHT: card */}
        <div
          style={{
            border: "1px solid #2a2a3e",
            borderRadius: "12px",
            padding: "16px",
            background: "#12121a",
            boxShadow: "0 1px 3px rgba(0,0,0,0.4)",
            transition: "transform 200ms ease, box-shadow 200ms ease",
            color: "#cccccc",
          }}
          onMouseEnter={(e) => {
            e.currentTarget.style.transform = "translateY(-4px)";
            e.currentTarget.style.boxShadow =
              "0 10px 20px rgba(0,0,0,0.6)";
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.transform = "translateY(0px)";
            e.currentTarget.style.boxShadow =
              "0 1px 3px rgba(0,0,0,0.4)";
          }}
        >
          <h3
            style={{
              fontSize: "18px",
              fontWeight: 600,
              marginBottom: "8px",
              color: "#cccccc",
            }}
          >
            Positionless index is the central predictor after adjusting for other variables.
          </h3>

          <p
            style={{
              fontSize: "14px",
              color: "#aaaaaa",
              lineHeight: 1.4,
            }}
          >
            Positionless index was the most important variable in predicting injury risk.
            After controlling for workload, playstyle, and team context, this variable remains important.
          </p>
        </div>
      </div>
    </section>
  );
}